Worksheet-1

Problem - 1: Array Creation:




In [ ]:
import numpy as np

#num1
empty_array= np.empty((2,2))
print( empty_array)
print("\n")

#num2
all_ones_array= np.ones((4,2))
print(all_ones_array)
print("\n")

#num3
fill_value_array = np.full((3,3),7)
print(fill_value_array)
print("\n")

#num4
my_array = np.array([[1, 2], [3, 4]])
zeros_like_array = np.zeros_like(my_array)
print(zeros_like_array)
print("\n")

#num5
my_array = np.array([[1, 2], [3, 4]])
ones_like_array = np.ones_like(my_array)
print(ones_like_array)
print("\n")

#num6
my_list = [1, 2, 3, 4]
numpy_array = np.array(my_list)
print(numpy_array)
print("\n")


[[4.9e-324 9.9e-324]
 [1.5e-323 2.0e-323]]


[[1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]


[[7 7 7]
 [7 7 7]
 [7 7 7]]


[[0 0]
 [0 0]]


[[1 1]
 [1 1]]


[1 2 3 4]




Problem - 2: Array Manipulation: Numerical Ranges and Array indexing:


In [ ]:
import numpy as np
arr = np.arange(11,50)
print(arr)

matrix = np.arange(9).reshape(3,3)
print(matrix)

identity = np.eye(3)
print(identity)
print("\n")

random_array = np.random.random(size=30)
print(random_array)
print("The mean of the above array is: ",random_array.mean())
print("\n")

random_array = np.random.random((10,10))
print(random_array)
print("Minimum Value is ",random_array.min())
print("Maximum Value is ",random_array.max())
print("\n")

zero_arr = np.zeros(10)
print(zero_arr)
zero_arr[5]=1
print(zero_arr)
print("\n")

arr = [1,2,0,0,4,0]
rev = np.flip(arr)
print(rev)

array = np.zeros((5, 5), dtype=int)

array[0, :] = 1
array[-1, :] = 1
array[:, 0] = 1
array[:, -1] = 1

print(array)
print("\n")

checkerboard = np.zeros((8, 8), dtype=int)


checkerboard[::2, ::2] = 1
checkerboard[1::2, 1::2] = 1

print(checkerboard)


[11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34
 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]
[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


[0.24001431 0.48259165 0.5885965  0.33993604 0.89010244 0.66641117
 0.38301421 0.75045785 0.15329402 0.68657717 0.15095473 0.132555
 0.13283478 0.06099491 0.53970576 0.88343242 0.98985798 0.72719713
 0.02599036 0.21011163 0.70734706 0.07056862 0.320246   0.39277908
 0.73909821 0.31390535 0.9158082  0.37595434 0.86156088 0.78783268]
The mean of the above array is:  0.4839910161892158


[[0.93400849 0.13577206 0.71161817 0.93893358 0.07980872 0.67971368
  0.31680391 0.09652942 0.26096474 0.84042024]
 [0.38319144 0.2084951  0.56829609 0.70750208 0.67834218 0.42291633
  0.20420956 0.40202255 0.24052288 0.29691008]
 [0.48493361 0.96926538 0.86759776 0.56384707 0.7226835  0.82276659
  0.82855745 0.10846479 0.97857973 0.49155855]
 [0.22194928 0.0193737  0.54275998 0.5675949  0.18520974 0.71612494
  0.10162979

Problem - 3: Array Operations:


In [5]:

x = np.array([[1, 2], [3, 5]])
y = np.array([[5, 6], [7, 8]])
v = np.array([9, 10])
w = np.array([11, 12])


add_xy = x + y
print("Addition of x and y:\n", add_xy)

subtract_xy = x - y
print("Subtraction of x and y:\n", subtract_xy)

multiply_x = 3 * x
print("Multiplication of x with 3:\n", multiply_x)

square_x = np.square(x)
print("Square of each element in x:\n", square_x)

dot_vw = np.dot(v, w)
print("Dot product of v and w:", dot_vw)

dot_xv = np.dot(x, v)
print("Dot product of x and v:", dot_xv)

dot_xy = np.dot(x, y)
print("Dot product of x and y:\n", dot_xy)


concat_xy_rows = np.concatenate((x, y))
print("Concatenation of x and y along rows:\n", concat_xy_rows)

concat_vw_columns = np.vstack((v, w))
print("Concatenation of v and w along columns:\n", concat_vw_columns)

try:
    concat_xv = np.concatenate((x, v))
    print("Concatenation of x and v:\n", concat_xv)
except ValueError as e:
    print("Error while concatenating x and v:", e)


Addition of x and y:
 [[ 6  8]
 [10 13]]
Subtraction of x and y:
 [[-4 -4]
 [-4 -3]]
Multiplication of x with 3:
 [[ 3  6]
 [ 9 15]]
Square of each element in x:
 [[ 1  4]
 [ 9 25]]
Dot product of v and w: 219
Dot product of x and v: [29 77]
Dot product of x and y:
 [[19 22]
 [50 58]]
Concatenation of x and y along rows:
 [[1 2]
 [3 5]
 [5 6]
 [7 8]]
Concatenation of v and w along columns:
 [[ 9 10]
 [11 12]]
Error while concatenating x and v: all the input arrays must have same number of dimensions, but the array at index 0 has 2 dimension(s) and the array at index 1 has 1 dimension(s)


Problem - 4: Matrix Operations:


In [4]:

import numpy as np
A = np.array([[3, 4], [7, 8]])
B = np.array([[5, 3], [2, 1]])

A_inv = np.linalg.inv(A)
identity_matrix = np.dot(A, A_inv)
print(np.allclose(identity_matrix, np.eye(2)))

AB = np.dot(A, B)
BA = np.dot(B, A)
AB_equals_BA = np.array_equal(AB, BA)
print(AB_equals_BA)

AB_transpose = np.transpose(AB)
B_transpose_A_transpose = np.dot(np.transpose(B), np.transpose(A))
AB_transpose_equals_BT_AT = np.array_equal(AB_transpose, B_transpose_A_transpose)
print(AB_transpose_equals_BT_AT)

A = np.array([[2, -3, 1], [1, -1, 2], [3, 1, -1]])
B = np.array([-1, -3, 9])
A_inv = np.linalg.inv(A)
X = np.dot(A_inv, B)
print("The solution is:\n", X)

True
False
True
The solution is:
 [ 2.  1. -2.]


In [10]:

import numpy as np
from time import time
list_size = 1_000_000

start_time = time()
list1 = [i for i in range(list_size)]
list2 = [i for i in range(list_size)]
list_addition = [list1[i] + list2[i] for i in range(list_size)]
list_addition_time = time() - start_time
print(f"Start Time: {start_time}\nEnd Time: {list_addition_time}")

array1 = np.arange(list_size)
array2 = np.arange(list_size)
start_time = time()
array_addition = array1 + array2
array_addition_time = time() - start_time
print(f"Start Time: {start_time}\nEnd Time: {array_addition}")

start_time = time()
list_multiplication = [list1[i] * list2[i] for i in range(list_size)]
list_multiplication_time = time() - start_time
print(f"Start Time: {start_time}\nEnd Time: {list_multiplication_time}")

start_time = time()
array_multiplication = array1 * array2
array_multiplication_time = time() - start_time
print(f"Start Time: {start_time}\nEnd Time: {array_multiplication_time}")

start_time = time()
list_dot_product = sum(list1[i] * list2[i] for i in range(list_size))
list_dot_product_time = time() - start_time
print(f"Start Time: {start_time}\nEnd Time: {list_dot_product_time}")

start_time = time()
array_dot_product = np.dot(array1, array2)
array_dot_product_time = time() - start_time
print(f"Start Time: {start_time}\nEnd Time: {array_dot_product_time}")

matrix_size = 1000
matrix1 = [[i for i in range(matrix_size)] for _ in range(matrix_size)]
matrix2 = [[i for i in range(matrix_size)] for _ in range(matrix_size)]
start_time = time()
matrix_multiplication = [
    [sum(matrix1[i][k] * matrix2[k][j] for k in range(matrix_size)) for j in range(matrix_size)]
    for i in range(matrix_size)
]
list_matrix_multiplication_time = time() - start_time
print(f"Start Time: {start_time}\nEnd Time: {list_matrix_multiplication_time}")

array_matrix1 = np.arange(matrix_size**2).reshape(matrix_size, matrix_size)
array_matrix2 = np.arange(matrix_size**2).reshape(matrix_size, matrix_size)
start_time = time()
array_matrix_multiplication = np.dot(array_matrix1, array_matrix2)
array_matrix_multiplication_time = time() - start_time
print(f"Start Time: {start_time}\nEnd Time: {array_matrix_multiplication_time}")

Start Time: 1733155883.1196592
End Time: 0.2855265140533447
Start Time: 1733155883.4134178
End Time: [      0       2       4 ... 1999994 1999996 1999998]
Start Time: 1733155883.445715
End Time: 0.15020155906677246
Start Time: 1733155883.5961244
End Time: 0.002465963363647461
Start Time: 1733155883.5987942
End Time: 0.15901851654052734
Start Time: 1733155883.7580488
End Time: 0.0019690990447998047


KeyboardInterrupt: 